### ISSUE TITLE
Histogram documentation is (possibly) incorrect

### ISSUE THREAD

**Issue by scimas** [d3/d3-array#106]
The [d3 API Reference](https://github.com/d3/d3/blob/master/API.md) links to [d3 array README](https://github.com/d3/d3-array/blob/master/README.md#histogram). A search for the string 'histogram' on this page leads you to the `Bins` section (and no other place).

This section lists `d3.bin()` as the histogram/bins generator. But trying to use `d3.bin()` results in the browser complaining `TypeError: d3.bin is not a function`. I assume this is because, as of version 5, there _is no_ `d3.bin` function. That the documentation has been changed as per future (past ?) plans by mistake. Because `d3.histogram` still works.

**Comment by mbostock** [comment]
d3.bin is the new name for d3.histogram in d3-array@2, which will be part of d3@6.

**Comment by scimas** [comment]
But since we are still on v5, shouldn't it remain d3.histogram for now? I think it is hard enough to figure out how things work in d3 for a newcomer like me without the API reference giving you wrong information. All top results for a "d3 histogram" google search use d3 v4 or v3, so you can't be sure whether the code is up to date or not. And indeed the d3.layout.histogram from v3 doesn't work any more.

**Comment by mbostock** [comment]
The API links from the d3 API.md aren’t versioned. If you’d like to contribute versioned links, that would be a welcome PR.
