### ISSUE TITLE
d3.merge(iterables[, accessor]) ?

### ISSUE THREAD

**Issue by xavierguihot** [d3/d3-array#116]
I noticed that most of the time when I use `d3.merge`, I need to `map` my input array to access the lists to flatten.

With almost all `d3.array` functions providing an optional accessor, `d3.merge` would probably also benefit from having an accessor parameter.

**Comment by mbostock** [comment]
Have you tried [*array*.flatMap](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap)? Some examples here:

https://observablehq.com/@d3/d3-merge

**Comment by xavierguihot** [comment]
Damn, last I tried using `flatMap` it wasn't part of javascript!
Indeed, thanks!
