### ISSUE TITLE
variance math is wrong

### ISSUE THREAD

**Issue by frankhhuo** [d3/d3-array#122]
for example, when calculating d3.variance([1,2,3]), it returns 1; the correct value is 0.6666

Problem was caused by the wrong values of mean in the code.  "mean" is changing in the loop!

**Comment by mbostock** [comment]
Looks correct to me:

https://observablehq.com/d/572f1ed498095767

**Comment by frankhhuo** [comment]
I think you used a different definition than Python numpy. The same
numbers, numpy returns different values.
Hongfa

**Comment by mbostock** [comment]
numpy’s ddof argument defaults to zero, whereas in d3-array, it’s equivalent to ddof=1.

https://docs.scipy.org/doc/numpy/reference/generated/numpy.var.html
