### ISSUE TITLE
Median function inefficiently calls quantile method (instead of quantileSorted)?

### ISSUE THREAD

**Issue by jheer** [d3/d3-array#124]
The [median implementation](https://github.com/d3/d3-array/blob/master/src/median.js#L12) performs an array copy, runs quickselect, and then invokes `quantile`... which in turn performs an array copy, sorts the array, and then calls `quantileSorted`. This appears to be doing costly unnecessary extra work.

Should the `median` method be calling `quantileSorted` instead?

**Comment by mbostock** [comment]
Derp! Thanks for finding and fixing this.

**Comment by mbostock** [comment]
Fixed in #121.
