### ISSUE TITLE
What do I have to import in order to use d3.maxIndex()

### ISSUE THREAD

**Issue by konradjurk** [d3/d3-array#127]
I've installed and imported `d3/dist/d3.min.js` and `d3-array/dist/d3-array.min.js`.

However, there is no d3.maxIndex method, though the documentation suggests that it lives inside the d3-array project: https://github.com/d3/d3-array#maxIndex. What am I doing wrong?

d3@5.12.0
d3-array@1.2.4

**Comment by konradjurk** [comment]
Got it, it has been introduced in `d3-array` v2.1. 

Is there a reason why even the latest d3 release still attracts a the outdated `d3-array` release 1.2.4?

**Comment by mbostock** [comment]
Yes, d3@6 has not been released yet. https://github.com/d3/d3/issues/3333
