### ISSUE TITLE
new version error：unexpected: name count

### ISSUE THREAD

**Issue by Leannechn** [d3/d3-array#129]
![image](https://user-images.githubusercontent.com/6812138/68567325-b749eb80-0493-11ea-834d-81adf84aabd5.png)

**Comment by Leannechn** [comment]
dist/count.js

```
let count = 
```

**Comment by Fil** [comment]
Can you clarify how you reach that situation?
There is no file in this repo named dist/count.js and there is no occurrence of  `let count = ` that stops at that point.

**Comment by Leannechn** [comment]
Sorry the question is from d3-geo

**Comment by Fil** [comment]
discussed in https://github.com/d3/d3-geo/issues/176
