### ISSUE TITLE
d3.group is not a function

### ISSUE THREAD

**Issue by jasli2** [d3/d3-array#131]
Using d3 v5.12.0 from cdn: 
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/5.12.0/d3.min.js" integrity="sha256-+9Mf3cAVmxxudDsr1XwXUeRZFtvdWVYdq5/vcgiYyNU=" crossorigin="anonymous"></script>
```

But report error: `TypeError: d3.group is not a function`.

Plase help.

**Comment by Fil** [comment]
d3.group is available with d3-array@2 ; but d3@5 includes d3-array@1

**Comment by jasli2** [comment]
@Fil Thanks for your comment. Which d3 version will includes d3-array@2?

**Comment by Fil** [comment]
It's planned for d3@6 — no release date has been announced yet.
