### ISSUE TITLE
Can't access d3.count unless library is called.

### ISSUE THREAD

**Issue by charlieartist** [d3/d3-array#133]
I'm building visualizations using the latest complete D3 library.

When attempting to add `d3.count`, though, this error is returned:
`Unhandled Promise Rejection: TypeError: d3.count is not a function.`

Other methods in this module such as `d3.mean` or `d3.min` work fine, though.

Currently, I avoid these errors by loading this module, as well as the D3 library.

**Comment by Fil** [comment]
d3.count was introduced in [d3-array@2.1.0](https://github.com/d3/d3-array/releases/tag/v2.1.0), which is not yet part of the d3 bundle. Will be with d3@6.
