### ISSUE TITLE
Bug: Array.from(rollup).sort not working on mobile device

### ISSUE THREAD

**Issue by AdrienLemaire** [d3/d3-array#135]
Test application: https://adrienlemaire.github.io/stash_support/

Broken Mobile browser rendering:
![Screenshot_20200129-155046](https://user-images.githubusercontent.com/260983/73334299-b4e77880-42af-11ea-8c07-cb42d4775670.png)

Desktop browser rendering with mobile resolution looks fine:
![image](https://user-images.githubusercontent.com/260983/73334354-d9435500-42af-11ea-8f2a-37638fd1e980.png)

Relevant code that's applied for the line:
```js
  // The rolledData returns tuples of (date, distance)
  const rolledData = d3array.rollup(
    data.filter(d => d.fullName.startsWith(name)),
    // group data by date and extract the highest score
    v => d3array.max(v, d => d.total),
    d => +d.date
  );
  const lineGenerator = d3shape
    .line()
    .x(d => window.timeScale(d[0])) // rolledData tuple
    .y(d => window.distanceScale(d[1]))
    .curve(d3shape.curveBundle.beta(0.9));

  const pathData = lineGenerator(
    Array.from(rolledData).sort((a, b) => +a[0] < +b[0])
  );

  userLine
    .attr("d", pathData)
    .style("fill", "transparent")
    .classed("text-purple-700", true)
    .attr("stroke-width", 4);
```
Assumption: the data is not reordered with `Array.from(rolledData).sort((a, b) => +a[0] < +b[0])`. 

That behavior can be reproduced on desktop by removing the `.sort()` part (`const pathData = lineGenerator(Array.from(rolledData));`)

**Comment by Fil** [comment]
a sort function should return 1 or -1, not 0 (except for equality).
Can you try changing to, e.g., `.sort((a, b) => +a[0] - +b[0])`?

**Comment by Fil** [comment]
see  https://observablehq.com/@d3/d3-ascending

**Comment by AdrienLemaire** [comment]
Many thanks @Fil !
