### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [d3/d3-array#137]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by mbostock** [comment]
I’m not interested in supporting TypeScript, but you’re welcome to maintain your own bindings and share them with folks!

**Comment by gordonwoodhull** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/d3-array

**Comment by sean-krail** [comment]
That package is out of date. It hasn't been updated since Feb 20, 2019. I'm running into issues because it's missing `least` for instance.
