### ISSUE TITLE
group is missing with npm install

### ISSUE THREAD

**Issue by manju-reddys** [d3/d3-array#141]
In `package.json` I have added `d3: 5.15.1` as dependency and after installation the all the functionalities of `group.js` were missing upon checking the `node_modules` I found that `group.js` is missing in the source.

<img width="577" alt="image" src="https://user-images.githubusercontent.com/1906881/78311903-022dd380-7507-11ea-8edd-425e6561dcf8.png">

**Comment by mbostock** [comment]
d3.group is available in d3-array@2 which will be released in d3@6.
