### ISSUE TITLE
Array.ticks returns ticks outside domain

### ISSUE THREAD

**Issue by dson** [d3/d3-array#162]
Array.ticks sometimes returns ticks outside the domain. This is inconsistent with the documentation, that says: each returned tick t satisfies start ≤ t and t ≤ stop. This behavior was introduced in 2.5.0, and probably caused by commit https://github.com/d3/d3-array/commit/f5883f640bec70926823d733fd68d1036d73d3f2.

Example, where tick 3 is outside domain [0, 2.2]:
```
array.ticks(0, 2.2, 3) // [0, 1, 2, 3]
```

**Comment by Fil** [comment]
Confirmed (both the bug and the commit reference).

**Comment by mbostock** [comment]
Good find!

**Comment by jheer** [comment]
Thanks @dson for filing the issue. This is breaking Vega as well!
