### ISSUE TITLE
Set operations: intersection, union, difference, etc.

### ISSUE THREAD

**Issue by mbostock** [d3/d3-array#173]
https://docs.python.org/3/library/stdtypes.html#set

**Comment by curran** [comment]
Would these work with instances of `Set` or `Array`?

Related:
 * https://lodash.com/docs/4.17.15#union
 * https://lodash.com/docs/4.17.15#intersection
 * https://lodash.com/docs/4.17.15#difference

**Comment by mbostock** [comment]
They work with any iterable but they return sets.
