### ISSUE TITLE
Add fcumsum?

### ISSUE THREAD

**Issue by Fil** [d3/d3-array#190]
~~~js
function fcumsum(values, valueof) {
  const sum = new d3.Adder();
  let index = 0;
  return Float64Array.from(values, valueof === undefined
      ? v => sum.add(+v || 0)
      : v => sum.add(+valueof(v, index++, values) || 0)
  );
}
~~~
https://observablehq.com/@d3/d3-fcumsum

ref. https://github.com/pbeshai/tidy/pull/2#issuecomment-772838271

**Comment by Fil** [comment]
In [this benchmark](https://observablehq.com/@fil/fcumsum-benchmark), fcumsum takes about 60% more time to compute than cumsum.

**Comment by mbostock** [comment]
Sounds good to me. It’s tiny and happy to add it.
