### ISSUE TITLE
import from d3-array

### ISSUE THREAD

**Issue by The-Igor** [d3/d3-array#211]
Hi, I'm trying to add d3-array as a module. I need a simple playground to play with the code.

This works perfectly, I get what I expect without errors 

```
<script type="module">
   import * as d3 from "./node_modules/d3-selection/src/index.js"
    d3.select("body").append("h1").text("Hello, world!");
</script>
```
I checked out **d3-color**, **d3-quadtree**  it's also nice no issues

<img width="787" alt="Screenshot 2021-06-05 at 11 22 39" src="https://user-images.githubusercontent.com/2305808/120885200-58f1da00-c5f0-11eb-8842-3c3654ba322c.png">
<img width="712" alt="Screenshot 2021-06-05 at 11 13 02" src="https://user-images.githubusercontent.com/2305808/120884986-0fed5600-c5ef-11eb-9e2b-c8d11bb8d301.png">

**but this does not work**

```
<script type="module">
    import * as d3 from "./node_modules/d3-array/src/index.js"
    var a = [0, 10, 30];
    console.log(d3.quantile(a, 1))
</script>
```

get an error 

_Any suggestion how to get away with the error ?_

<img width="963" alt="Screenshot 2021-06-05 at 11 08 00" src="https://user-images.githubusercontent.com/2305808/120884989-124fb000-c5ef-11eb-8cbb-b70ceb6202ac.png">

package.json, just in case what versions I use

  "devDependencies": {
    "d3-quadtree": "3.0.0",
    "d3-color": "3.0.0",
    "d3-selection": "2.0.0",
    "d3-array": "2.12.1"
  }

**Comment by mbostock** [comment]
The error in your console explains the issue. It’s referring to this line here (among others):

https://github.com/d3/d3-array/blob/6fda2773d31c2b3377d8b2dbd11a3e334a7cbc9e/src/group.js#L1

This is known as a “bare import”, mean that it’s of something defined in the package.json and published to the npm package registry, not a relative path or URL. There are two ways to load such ES modules in browsers:

1. Use an [import map](https://wicg.github.io/import-maps/). (Only supported in Chrome; I’ve never tried.)
2. Use a bundler.

If you are running the bundler locally, I recommend Rollup. If you want something you can run in the cloud, I recommend Skypack. For example:

```html
<script type="module">

import {quantile} from "https://cdn.skypack.dev/d3-array";

console.log(quantile([0, 10, 30], 1));

</script>
```

**Comment by The-Igor** [comment]
Mike, thank you for comprehensive answering
Thank you for your work it's incredible
