### ISSUE TITLE
jest failed when upgrade d3-array to the latest version

### ISSUE THREAD

**Issue by visiky** [d3/d3-array#212]
![image](https://user-images.githubusercontent.com/15646325/121042985-cc5d3c80-c7e6-11eb-9bd0-978d5e79e874.png)

**Comment by visiky** [comment]
I fix this error by specify version to `2.12.1`, such as:
```ts
 "resolutions": {
    "d3-array": "2.12.1"
  }
```

**Comment by Fil** [comment]
Yes. See https://github.com/d3/d3-array/releases/tag/v3.0.0 and https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c for details.
