### ISSUE TITLE
Development Server Failing in Next.js

### ISSUE THREAD

**Issue by csandman** [d3/d3-array#213]
I am currently using this file in my next.js project and upgrading to `v3.0.1` broke our development server because for whatever reason, Next.js uses only CJS format modules.

I was wondering if there was any reason for removing Common JS support in this version?  I know rollup can easily handle exporting both a CJS and ESM output so it seems pointless to remove it.

**Comment by mbostock** [comment]
https://github.com/d3/d3-array/releases/tag/v3.0.0

**Comment by mbostock** [comment]
And specifically https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#im-having-problems-with-esm-and-nextjs
