### ISSUE TITLE
Docs: define the bin thresholds with array 

### ISSUE THREAD

**Issue by Benbinbin** [d3/d3-array#244]
the document [says](https://github.com/d3/d3-array#bin_thresholds)

> Thresholds are defined as an array of values [x0, x1, …]. Any value less than x0 will be placed in the first bin; any value greater than or equal to x0 but less than x1 will be placed in the second bin; and so on.

I think the above description means the first bin range is `(-∞, x0)`, the second bin range is `[x0, x1)`

in the other part it also describes the thresholds as below

> Any threshold values outside the domain are ignored. The first bin.x0 is always equal to the minimum domain value, and the last bin.x1 is always equal to the maximum domain value.

it means the first bin range is `[x0, x1)` or `[min, x1)`

the different descriptions about first bin confuse me.

**Comment by Fil** [comment]
Would it be clearer if we changed the names of threshold values to t0 t1 etc? It would read:

> Thresholds are defined as an array of values [t0, t1, …]. Any value less than t0 will be placed in the first bin; any value greater than or equal to t0 but less than t1 will be placed in the second bin; and so on.

> Any threshold values outside the domain are ignored. The first bin.x0 is always equal to the minimum domain value, and the last bin.x1 is always equal to the maximum domain value.

Then it's less confusing maybe, since the first bin’s x0 is described as min(values), and the first bin's x1 is t0?

**Comment by Benbinbin** [comment]
Thanks!
