### ISSUE TITLE
First and last thresholds are set to data extent (not explicitly stated limits)

### ISSUE THREAD

**Issue by mkfreeman** [d3/d3-array#245]
Based on the [documentation](https://github.com/d3/d3-array/blob/main/README.md#bin_thresholds), _Thresholds are defined as an array of values [x0, x1, …]_. Given that, I would expect the bin limits (`x0`, `x1`) to match the threshold arguments. However, the `x0` of the first bin is set to the data minimum, and the `x1` of the last bin is set to the data maximum. For example:

```js
// expect x0:1, x1: 2, but returns x0: 1.5, x1: 1.5
d3.bin().thresholds([1, 2])([1.5]).map(d => ({x0: d.x0, x1: d.x1}))
```

**Comment by mbostock** [comment]
See bin.domain:

> Any threshold values outside the [domain](https://github.com/d3/d3-array/issues/245#bin_domain) are ignored. The first bin.x0 is always equal to the minimum domain value, and the last bin.x1 is always equal to the maximum domain value.

**Comment by mkfreeman** [comment]
Thanks for clarifying!
