### ISSUE TITLE
About the sorting problem of d3.rank

### ISSUE THREAD

**Issue by xuan-zai** [d3/d3-array#266]
In my tests, I encountered one of the following problem:
- The following problem occurs when the array contains both a number and an English string or {}, and the array is of length 3, which I think is pretty bad, though it's rarely used in my work
    - `d3.rank([1, 't', 0]); // The output result is:[0, NaN, NaN]  But here's what I'm thinking: [1, NaN, 0]`
    - `d3.rank([1, {}, 0]); // The output result is:[0, NaN, NaN]  But here's what I'm thinking: [1, NaN, 0]`

**Comment by Fil** [comment]
d3.sort gives the same order

> d3.sort([1, "t", 0]) // [1, "t", 0]

**Comment by xuan-zai** [comment]
It may be that my example is too extreme. I should seldom encounter it in my work。
