### ISSUE TITLE
Add comparator()?

### ISSUE THREAD

**Issue by herrstucki** [d3/d3-array#29]
I made https://github.com/interactivethings/d3-comparator a while back and want to use it again. It uses the old d3 global extension mechanism though, so I'd need to update it. I wondered if I should update it to work properly with npm/rollup, decouple it from d3 entirely or if I should make a PR to this library? Do you think it would be a good fit for d3-array?

**Comment by mbostock** [comment]
I’d definitely recommend adopting the [D3 module pattern](https://bost.ocks.org/mike/d3-plugin/). Despite the name, your module needn’t have any D3 dependencies for it to make sense to use this pattern; see the standalone [d3-queue](https://github.com/d3/d3-queue) library for instance.

As for including this in d3-array, well, it’s not really to my taste. Sorry. I tend to prefer using `||` for composite comparators. To take your example:

```js
var cmp = d3.comparator()
  .order(d3.descending, function(d) { return d.year; })
  .order(d3.ascending, function(d) { return d.value; });
```

I’d probably write this as:

```js
function cmp(a, b) {
  return b.year - a.year
      || a.value - b.value;
}
```

Or, if `value` is something else naturally comparable (like a Date or string), I might say:

```js
function cmp(a, b) {
  return b.year - a.year
      || ascending(a.value, b.value);
}
```

**Comment by mbostock** [comment]
Also, regarding:

> Constructs a new comparator with the default return value 0. I.e. using it will not change sort order.

A comparator that returns 0 (or NaN) isn’t guaranteed to not change the sort order; that’s only the case for stable sorting algorithms, and ECMAScript doesn’t require that *array*.sort is stable. ([Related StackOverflow.](https://stackoverflow.com/questions/3026281/array-sort-sorting-stability-in-different-browsers))
