### ISSUE TITLE
d3.histogram shouldn’t coerce ordinal input to numbers.

### ISSUE THREAD

**Issue by cpietsch** [d3/d3-array#34]
Lets say you have a 
`let x = d3.scaleTime()`

and you want to use it on an histogram

```
d3.histogram()
  .value(d=> d.date)
  .domain(x.domain())
  .thresholds(x.ticks(d3.timeYear, 1))
```

**Comment by mbostock** [comment]
Yes, that’s valid. Is there a question? Here’s an example:

[![preview](https://cloud.githubusercontent.com/assets/230541/15903465/c0be0fe6-2d61-11e6-9cf0-7e6a9ba8bd9d.png)](http://bl.ocks.org/mbostock/b2fee5dae98555cf78c9e4c5074b87c3)

**Comment by cpietsch** [comment]
Oh sorry. I got confused by the negative x0/x1 values. Was expecting a date object or a positive value.

**Comment by mbostock** [comment]
Ah. Well yes, the *bin*.x0 and *bin*.x1 are coerced to numbers. And so are the other parts of the histogram (the domain, the values, the thresholds). However, it occurs to me that this is overly strict, and really the histogram only requires comparable (ordinal) values and not numbers, so we could relax that and leave dates as dates.

**Comment by lgrkvst** [comment]
Observation: if `.value()` returns `Date` objects, the first element's `x0` and the last element's `x1` will stay `Date` objects. The bin thresholds in-between is coerced into `number`objects.
<pre>
var A = [1476448344837, 1476448348221, 1476448350581, 1476448352482];
var yay = d3.histogram().value(a => a)(A); // all numbers
var nay = d3.histogram().value(a => new Date(a))(A); // Date objects for `nay[0].x0` and `nay[1].x1`
</pre>
