### ISSUE TITLE
transpose and zip should use max rather than min length?

### ISSUE THREAD

**Issue by mbostock** [d3/d3-array#49]
Related #48. This would be a breaking change, though, presumably.

**Comment by Fil** [comment]
The "losing data" feature is documented in https://observablehq.com/d/06cacb8a32da04c7; I don't see a practical use for it (if we want to eliminate nulls then an explicit filter or slice would be better).

**Comment by mbostock** [comment]
Yep, let’s be conservative and not change behavior unless we feel strongly about it.
