### ISSUE TITLE
Histogram Blur / Smoothing

### ISSUE THREAD

**Issue by curran** [d3/d3-array#56]
It would be useful to have a "blur" function to approximate kernel density estimation.

This function would accept the output from `histogram`, conceptually looking something like:

```js
blur(histogram(data))
```

Original discussion in https://github.com/d3/d3-contour/issues/7#issuecomment-293321567

The implementation could be similar to [blurX or blurY in d3-contour](https://github.com/d3/d3-contour/blob/2fd7927e8c3ba2a7cf01bc0688ae0b2d2c1bf6ae/src/blur.js#L4).

This article may be relevant: [Convolve n Square Pulses to Gaussian](https://oscar6echo.blogspot.in/2012/10/convolve-n-square-pulses-to-gaussian.html).

**Comment by curran** [comment]
Mind blown after seeing this

>Due to the central limit theorem, the Gaussian can be approximated by several runs of a very simple filter such as the moving average. The simple moving average corresponds to convolution with the constant B-spline ( a rectangular pulse ), and, for example, four iterations of a moving average yields a cubic B-spline as filter window which approximates the Gaussian quite well.

from [Wikipedia: Gaussian filter](https://en.wikipedia.org/wiki/Gaussian_filter).

Makes me wonder if we could add moving average functionality to d3-array as well, then use that to implement `blur`.

**Comment by curran** [comment]
I did an experiment and found that moving averages do seem to converge on what looks like a Gaussian.

[![image](https://cloud.githubusercontent.com/assets/68416/24948503/1f181f28-1f88-11e7-89ca-9050a0792fad.png)](https://bl.ocks.org/curran/853fa00b8f0732fb2bee7fccfd7b4523)
https://bl.ocks.org/curran/853fa00b8f0732fb2bee7fccfd7b4523

Also related to https://github.com/d3/d3-shape/issues/43

**Comment by curran** [comment]
I keep coming across scenarios where a bit of smoothing would be useful, for example this one:

![image](https://user-images.githubusercontent.com/68416/35920761-c64326fa-0c3e-11e8-98ae-eaf7acf4879c.png)

[CO2 Emissions Stacked Area Chart](https://datavis.tech/vis/3f5e0ba76cbf405e9fd87201bf21cac6)

**Comment by curran** [comment]
Proposed implementation:

```js
const blur = (data, property) => data.map((d, i) => {
  const previous = (i === 0) ? i : i - 1;
  const next = (i === data.length - 1) ? i : i + 1;
  const sum = data[previous][property] + d[property] + data[next][property];
  d[property] = sum / 3;
  return d;
});
```

**Comment by Fil** [comment]
Moving average: https://observablehq.com/@d3/moving-average
(would be great to have it in d3-array)

**Comment by Fil** [comment]
Also did a Gaussian Smoothing notebook
https://observablehq.com/@fil/gaussian-smoothing
Obvious advantage over moving average is it's smoother :) It shows quite well on the electricity dataset which has a 24h base period.

**Comment by curran** [comment]
Here's an application of that blur function.

[![image](https://user-images.githubusercontent.com/68416/84085932-af641280-a9b4-11ea-8e1d-2f34d715df32.png)](https://vizhub.com/curran/14bdac88ebf747c2b8a9a919bbe0a831)

https://vizhub.com/curran/14bdac88ebf747c2b8a9a919bbe0a831

**Comment by Fil** [comment]
I think we would also want optimized 2D or n-D blurs, like we have in https://github.com/d3/d3-contour/blob/master/src/blur.js (note the number of TODO in the comments ;-) ).

**Comment by curran** [comment]
Yes that would be very cool!

One "problem" I notice with the Gaussian blur approach of repeated averaging is that the slope of the curves appear to tend towards zero the closer you get to the endpoints (see the red rectangle in the image).

![image](https://user-images.githubusercontent.com/68416/84438556-bc774080-ac04-11ea-8a4b-6eabf2cd01d6.png)

Is this a known problem with Gaussian blur in general? How to folks usually deal with this?

To me, it seems to skew the data into showing something that's not there (the "flattening out" effect at the end of the curve), which make the dataviz misleading. The original data does not seem to exhibit that behavior.

![image](https://user-images.githubusercontent.com/68416/84438879-3dced300-ac05-11ea-979a-547cbac1f989.png)

I'm thinking to just remove the data points that could have been indirectly impacted by the edge case - so chop off `numIterations` values from the beginning and end of the timeseries.

**Comment by curran** [comment]
Here's a revised implementation, taking that end flattening effect into account:

```js
export const blur = (data, property, numIterations) => {
  for (let j = 0; j < numIterations; j++) {
    for (let i = 0; i < data.length; i++) {
      const d = data[i];
      const previous = i === 0 ? i : i - 1;
      const next = i === data.length - 1 ? i : i + 1;
      const sum = data[previous][property] + d[property] + data[next][property];
      d[property] = sum / 3;
    }
  }
  // Chop off the ends, as they may represent misleading "flattening".
  return data.slice(numIterations, data.length - numIterations);
};
```

**Comment by Fil** [comment]
[Here's a fork](https://vizhub.com/Fil/949e4e1d874240b789bc05716e3a2ca7) which uses my [gaussian kernel blurring](https://observablehq.com/@fil/gaussian-smoothing); it doesn't seem to suffer from the problem you describe?

**Comment by curran** [comment]
Very nice! Indeed, the problem is not there. The problem must lie in the repeated iteration technique.

**Comment by Fil** [comment]
This new notebook shows how we could use the same API for 1D and 2D blur:
https://observablehq.com/@fil/moving-average-blur

I've also straightened the implementation a little to get more juice out of it (about 30% faster in my tests). I've tried to implemented gaussian blur but it does not compete at all in terms of speed.

**Comment by Fil** [comment]
And [here](https://vizhub.com/Fil/28261ccfe9dd43c096e90c4872eefd8c) is another fork, this time using the [d3.blur proposal](https://github.com/d3/d3-array/pull/151).

**Comment by curran** [comment]
To close the loop here, the [implementation](https://github.com/d3/d3-array/pull/151) was published as a separate package https://github.com/Fil/array-blur .
