### ISSUE TITLE
d3-array.range

### ISSUE THREAD

**Issue by deqingli** [d3/d3-array#57]
in range.js:
line6 :  range = new Array(n);
            while (++i < n) {
                  range[i] = start + i * step;
            }
I think it's should be :  range = new Array(n + 1);
                                     while (++i < (n + 1)) {
                                             range[i] = start + i * step;
                                     }
for example:
start = 65, stop = 85, step = 5 
n = Math.max(0, Math.ceil((stop - start) / step)) | 0 = 4
if range = new Array(n)
return range = [65, 70, 75, 80]
however , range = [65, 70, 75, 80, 85] may be needed.

**Comment by mbostock** [comment]
Per the documentation, the upper bound is exclusive, so 85 is not included in the returned array in your example.
