### ISSUE TITLE
Failed to minify code from this file	./node_modules/d3-array/src/rollup.js:3 

### ISSUE THREAD

**Issue by agupta93** [d3/d3-array#80]
While building with create-react-app getting the above error after the latest release

**Comment by agupta93** [comment]
Can someone please check it is getting a blocker for our release

**Comment by lucidfrontier45** [comment]
Looks like this commit caused the problem.
https://github.com/d3/d3-array/commit/729367edb0e51dc8c01ed91cc272bba9b26ef627#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R24

Webpack is trying to include rollup.js which contains ES6 expression and cannot be uglified.
Below is my error log
```
static/js/main.e63b9209.js from UglifyJs
Unexpected token: name (index) [./~/d3-array/src/rollup.js:3,0][static/js/main.e63b9209.js:47905,6]
```

**Comment by curran** [comment]
Can one of you provide a way to replicate the behavior? Ideally a complete repo where someone could clone it and run `npm start` or something in order to see the error. Thanks!

Also, what is the expected behavior? Uglify does not support ES6, which is not a problem with D3.

**Comment by lucidfrontier45** [comment]
I found the error only occurs with react-scripts v1.x and the error disappeared after upgrading to v2.

**Comment by mbostock** [comment]
Yes, I’m starting to adopt more recent ES features in D3 modules. I’m going to do a major version bump when I rewrite the array methods to allow iterables rather than just arrays, but the addition of d3.group and d3.rollup was backwards-compatible and thus only saw a minor version bump.

**Comment by agupta93** [comment]
@mbostock It is not currently backward compatible as we get this error while trying to build via react-scripts 1.x.x. Forcing an upgrade would not be a good solution

**Comment by mbostock** [comment]
The definition of backwards-compatible is subjective; see [Why Semantic Versioning Isn’t](https://gist.github.com/jashkenas/cbd2b088e20279ae2c8e) for context. At any rate, since I’m planning on following this up with a major version bump to switch to iterables, I’m happy to defer the addition of group and rollup to d3-array@2 (d3@6) and consequently have unpublished 1.3.0.

**Comment by agupta93** [comment]
If that could happen it would be really very helpful. Would save us a lot of trouble.
