### ISSUE TITLE
Transpile src?

### ISSUE THREAD

**Issue by vasturiano** [d3/d3-array#87]
As of `v2.0.0` `d3-array` is exposing non-ES5 code as part of the ES modules entry point `src/index.js`. F.e.:
https://github.com/d3/d3-array/blob/master/src/min.js#L2

I think this may be causing some building issues for consuming applications that assume the code is ES5 compatible and are not transpiling their `node_modules` (as is the norm).

Possibly `d3-array` should add a transpilation phase to the rollup builds and expose the `modules` entry point from the `dist` folder instead of `src` directly.

If it's of any help, I've done a similar thing to a `d3` plugin here:
 https://github.com/vasturiano/d3-geo-zoom

**Comment by curran** [comment]
Related to https://github.com/d3/d3-array/issues/80

This problem will keep coming up. It sounds like a good idea to deliver ES5 as the CommonJS entry point.

**Comment by mbostock** [comment]
Sorry, but I’ve switched to ES2015 going forward, and future major versions of D3 modules will be using ES2015. If you want to stick with ES5, you should stick with the previous major version. The primary reason that I will not provide transpilation to ES5 is that I want to use runtime features, not just syntax. That, and supporting ES5 environments will be an ongoing burden and I want D3 to have access to modern language features.

**Comment by mbostock** [comment]
Yep!

**Comment by JamesIves** [comment]
@mbostock Would you be able to add this to release notes for version 2.0.0? It was pretty hard to come by this thread and took a bit of debugging to figure out where this was coming from.
