### ISSUE TITLE
d3.group/d3.rollup not in default d3 bundle?

### ISSUE THREAD

**Issue by afdta** [d3/d3-array#88]
I saw the deprecation notice for d3.nest() when looking through the [d3-collection documentation](https://github.com/d3/d3-collection#d3-collection). So, I tried using d3.group(), only to find it's not available. I've upgraded to the latest version of d3 (via npm), but still don't see it.

**Comment by mbostock** [comment]
Correct. d3-array@2 will be available in d3@6, which is forthcoming.
