### ISSUE TITLE
d3.permute should inherit the type of the passed-in array.

### ISSUE THREAD

**Issue by mbostock** [d3/d3-array#92]
For example, if d3.permute a Int32Array, you should get back a new Int32Array.

**Comment by Fil** [comment]
would `permutes = array.slice(0, i)` be a solution? It passes all tests.

https://github.com/d3/d3-array/blob/master/src/permute.js#L2

**Comment by Fil** [comment]
my solution clashes with #93. Here's a solution that does both;
```
export default function(array, indexes) {
  var i = 0, permutes = array.slice();
  for (var p of indexes) permutes[i++] = array[p];
  return permutes.slice(0,i);
}
```

**Comment by mbostock** [comment]
On second thought, this can’t work because the source can be an object (as shown in the README) rather than an array, and this wouldn’t be backwards-compatible if people were expecting d3.permute to return an array when they pass in a typed array (so that they can *e.g.* subsequently push new values onto it).
