### ISSUE TITLE
d3.quantile is difficult to use

### ISSUE THREAD

**Issue by Fil** [d3/d3-array#97]
Although it's properly documented, it's easy to fall in the trap of forgetting to sort & filter the data, and a bit difficult to find the correct way to do it.

Shouldn't we have a slower but foolproof d3.quantile, and a fast d3.quantileRaw (or any other name) for the few people who know what they are doing?

Another way to look at this is that the reason for this behavior is to optimize when extracting several quantiles ; but then this could be rewritten as d3.quantile(values, fractions, accessor) where fractions is a list.

**Comment by mbostock** [comment]
I think d3.quantileSorted(*array*) and d3.quantile(*iterable*) would be nice.

**Comment by nite** [comment]
@Fil what do you mean sort sort **& filter** the data? I've just switched some code to mathjs.quantileSeq as I didnt know about this & thought it was a bug ;) (I knew it couldnt be)

**Comment by Fil** [comment]
I mean you need to filter out the NaN and undefined. Can you share an example that gives incorrect results?

**Comment by nite** [comment]
My apologies, when I actually dug in & looked at the arrays being sorted I realised it was just using a .sort & didnt know sort converts numbers to string then sorts! Crazy. Flipped to lodash sort & it works, cheers
